// <auto-generated />
using System;
using GaziKultur.Data.Concrete.EntityFramework;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GaziKultur.Data.Migrations
{
    [DbContext(typeof(GaziKulturContext))]
    [Migration("20260813081911_MuzeDetayAlanlariEklendi")]
    partial class MuzeDetayAlanlariEklendi
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GaziKultur.Entity.Concrete.Kutuphane", b =>
                {
                    b.Property<Guid>("KutuphaneID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AcilisSaati")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Adres")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Aktif")
                        .HasColumnType("bit");

                    b.Property<bool>("BilgisayarVarMi")
                        .HasColumnType("bit");

                    b.Property<bool>("CalismaAlaniVarMi")
                        .HasColumnType("bit");

                    b.Property<string>("CalismaGunleri")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EklenmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("HaritaLinki")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ilce")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("InternetVarMi")
                        .HasColumnType("bit");

                    b.Property<string>("Isim")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KapanisSaati")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KisaAciklama")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Resim")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("KutuphaneID");

                    b.ToTable("Kutuphaneler");
                });

            modelBuilder.Entity("GaziKultur.Entity.Concrete.Muze", b =>
                {
                    b.Property<Guid>("MuzeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AcilisSaati")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Adres")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Aktif")
                        .HasColumnType("bit");

                    b.Property<DateTime>("EklenmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("Eposta")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GirisUcreti")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GiseKapanisSaati")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HaritaLinki")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ilce")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Isim")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KapanisSaati")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KisaAciklama")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MuzekartBilgisi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Resim")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tarihce")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UcretEuro")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UcretTL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ZiyaretGunleri")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MuzeID");

                    b.ToTable("Muzeler");
                });
#pragma warning restore 612, 618
        }
    }
}
