<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <RootNamespace>GaziKultur.Entity</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\GaziKultur.Core\GaziKultur.Core.csproj" />
  </ItemGroup>

</Project>
