<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <RootNamespace>GaziKultur.WebAPI</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.10">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\GaziKultur.Core\GaziKultur.Core.csproj" />
    <ProjectReference Include="..\GaziKultur.Data\GaziKultur.Data.csproj" />
    <ProjectReference Include="..\GaziKultur.Entity\GaziKultur.Entity.csproj" />
    <ProjectReference Include="..\GaziKultur.Service\GaziKultur.Service.csproj" />
  </ItemGroup>

</Project>
